name: build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: PNPM setup
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Run eslint
        run: pnpm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: PNPM setup
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Run unit tests
        run: pnpm test
